baseURL = 'https://footballposition-soccer.pages.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
buildFuture = true
[pagination]
  pagerSize = 10

[params]
  #首页显示文章的分区；保留 posts 即可
  mainSections = ["posts"]

  #开启 PaperMod 的 Home Info 块（没有文章也能展示）
  [params.homeInfoParams]
    Title = "Test"
    Content = "Welcome"

[menu]
  [[menu.main]]
    name = "attacking-positions"
    url = "/attacking-positions/"
    weight = 10
  [[menu.main]]
    name = "midfield-positions"
    url = "/midfield-positions/"
    weight = 20
  [[menu.main]]
    name = "defensive-positions"
    url = "/defensive-positions/"
    weight = 30
