baseURL = 'https://footballposition-soccer.pages.dev/'
languageCode = 'en-us'
title = 'FootballPosition.soccer'
theme = "PaperMod"
buildFuture = true
[pagination]
  pagerSize = 10

[params]
  #首页显示文章的分区；保留 posts 即可
  mainSections = ["posts"]

  #开启 PaperMod 的 Home Info 块（没有文章也能展示）
  [params.homeInfoParams]
    Title = " FootballPosition.soccer – Master Every Role on the Pitch | Position Guides, Drills & Pro Tips"
    Content = "From goalkeeper to false nine, FootballPosition.soccer breaks down every football position’s duties, skill-set, tactical role and weekly training plans. Learn how to read the game, choose your gear and level up with position-specific drills used by pro clubs—all in clear, concise language for players, coaches and fans."

[menu]
  [[menu.main]]
    name = "Overview"
    url = "/overview/"
    weight = 5
  [[menu.main]]
    name = "AttackingPositions"
    url = "/attacking-positions/"
    weight = 10
  [[menu.main]]
    name = "MidfieldPositions"
    url = "/midfield-positions/"
    weight = 20
  [[menu.main]]
    name = "DefensivePositions"
    url = "/defensive-positions/"
    weight = 30

