baseURL = 'https://footballposition-soccer.pages.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
buildFuture = true
[pagination]
  pagerSize = 10

[params]
  #首页显示文章的分区；保留 posts 即可
  mainSections = ["posts"]

  #开启 PaperMod 的 Home Info 块（没有文章也能展示）
  [params.homeInfoParams]
    Title = "足球位置百科"
    Content = "欢迎来到本站。浏览上方菜单的各个栏目，或从 CMS 新建内容后这里会显示最新文章。"

[menu]
  [[menu.main]]
    name = "进攻位置"
    url = "/attacking-positions/"
    weight = 10
  [[menu.main]]
    name = "中场位置"
    url = "/midfield-positions/"
    weight = 20
  [[menu.main]]
    name = "防守位置"
    url = "/defensive-positions/"
    weight = 30
