backend:
  name: git-gateway
  identity_url: https://footballposition-soccer-identity.netlify.app/.netlify/identity
  gateway_url: https://footballposition-soccer-identity.netlify.app/.netlify/git
site_url: https://footballposition-soccer.pages.dev/
display_url: https://footballposition-soccer.pages.dev/
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "attacking-positions"
    label: "进攻位置"
    folder: "content/attacking-positions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "defensive-positions"
    label: "防守位置"
    folder: "content/defensive-positions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "midfield-positions"
    label: "中场位置"
    folder: "content/midfield-positions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}