backend:
  name: github
  repo: diegobona/footballposition-soccer-site
  branch: main
  api_root: https://api.github.com
site_url: https://footballposition-soccer.pages.dev/
publish_mode: simple
media_folder: "static/images"
public_folder: "/images"